use standard uint* instead of u_int*
thus fix building w/ musl

>image.c:466:5: error: unknown type name 'u_int32_t'; did you mean 'uint32_t'?
>  466 |     u_int32_t current_box_len = __bswap_32(*((u_int32_t*) avifhdr));
>      |     ^~~~~~~~~
>      |     uint32_t